---
- hosts: 172.31.10.246
  become: yes 
  tasks:
   - include_tasks: myfile.yml


   - name: i want to copy the file from master to node 
     copy:
      src: mystatic
      dest: /home/ubuntu/mystaticfile
