---
- hosts: 172.31.10.246
  become: yes 
  tasks:
   - include_tasks: myfile.yml


   - name: i want to copy the file from master to node 
     copy:
      src: mystatic
      dest: /home/ubuntu/mystaticfile

   - name : i want to install web server 
     apt:
      name: apache2
      state: present  

   - name: i want to copy the dynamic file 
     template:
       src: myindexfile.j2
       dest: /var/www/html/index.html
     notify: iwanttorestartmywebserver

   - name: i want download remote file
     get_url:
       url: https://lienzo.s3.amazonaws.com/images/bd791441603b8beaf14cd9e119133303-Simple-resume-template.pdf
       dest: /home/ubuntu/bd791441603b8beaf14cd9e119133303-Simple-resume-template.pdf
       force_basic_auth: yes

     handlers:
     - name: iwanttorestartmywebserver
       service:
        name: apache2
        state: restarted
