---
- hosts: 172.31.10.246
  become: yes 
  tasks:
   - include_tasks: myfile.yml


   - name: i want to copy the file from master to node 
     copy:
      src: mystatic
      dest: /home/ubuntu/mystaticfile

   - name : i want to install web server 
     apt:
      name: apache2
      state: present  

   - name: i want to copy the dynamic file 
     template:
       src:
       dest: /var/www/html/index.html
